name: study_flow
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  bloc: ^8.1.0
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  equatable: ^2.0.5
  flutter_bloc: ^8.1.1
  
  get_it: ^7.2.0
  injectable: ^2.1.0
  json_annotation: ^4.8.0
  lottie: ^2.6.0
  path: ^1.8.3
  percent_indicator: ^4.2.3
  shared_preferences: ^2.2.2
  sqflite: ^2.3.0
  audioplayers: ^5.2.1

  
 

dev_dependencies:
  bloc_test: ^9.1.0
  build_runner: ^2.3.3
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.1.3
  json_serializable: ^6.6.0
  mocktail: ^0.3.0
  test: null
  


flutter:
  generate: false
  uses-material-design: true
  assets:
    - assets/animations/
    - assets/fonts/
    - assets/icons/
    - assets/sounds/
    - assets/sql/
    
  fonts:
    - family: Mplus1p
      fonts:
        - asset: assets/fonts/MPLUS1p-Regular.ttf
        - asset: assets/fonts/MPLUS1p-Bold.ttf
          weight: 700
