name: study_flow

on:
  push:
    branches:
      - DEV-*

jobs:
  verify-flutter:
    uses: ./.github/workflows/flutter_package.yaml
    with:
      flutter_channel: 'stable'
      flutter_version: '3.10.6'
      min_coverage: 60
    # secrets:
    #   ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}

  verify-semantics-pull-request:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/semantic_pull_request.yml@v1

  build:
    needs:
      [
        verify-flutter,
        verify-semantics-pull-request,
      ]  
    runs-on: ubuntu-latest

    steps:
      - name: noop
        run: echo 'noop'
