name: Deployment in app distribution

on:
  pull-request:
    branches:
      - master

jobs:
  verify-flutter:
    uses: ./.github/workflows/flutter_package.yaml
    with:
      flutter_channel: 'stable'
      flutter_version: '3.10.6'
      min_coverage: 60
    # secrets:
    #   ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}

  verify-semantics-pull-request:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/semantic_pull_request.yml@v1

  build-android:
    needs:
      [
        verify-flutter,
        verify-semantics-pull-request,
      ] 

    runs-on: ubuntu-latest

    steps:
      - name: 🦾 Build Android APK
        run: flutter build appbundle 
  
  build-ois:
    needs:
      [
        verify-flutter,
        verify-semantics-pull-request,
      ]

    runs-on: macos-latest

    steps:
      - name: 🍎 Build iOS IPA
        run: flutter build ios --no-codesign
        
